import "../styles/global.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Deepnote",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="grid grid-cols-4"
      >
        <Sidebar />
        <div className="col-span-3">
        <Navbar />
        {children}
        </div>
      </body>
    </html>
  );
}
